<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;
var
	sModuleName: string;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	sModuleName := ChangeFileExt(ExtractFileName(HndGeneratorInfo.OutputFile), '').Replace(' ', '_');
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('# Project: %s', [HndProjects.GetProjectTitle()]);
	println ('# Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	println('from collections import namedtuple');
	println('');
	printfln('Help_%s = namedtuple("Help_%s", [', [sModuleName, sModuleName]);
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		if nCurTopic < length(aTopicList) - 1 then
			printfln('    "%s",', [aTopicList[nCurTopic].HelpId])
		else
			printfln('    "%s"', [aTopicList[nCurTopic].HelpId]);
	end;
	println('])');
	println('');
	printfln('help_topics = Help_%s(', [sModuleName]);
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		if nCurTopic < length(aTopicList) - 1 then
			printfln('    %s=%d,', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext])
		else
			printfln('    %s=%d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	println(')');
	
end.
%>
