<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('// Project: %s', [HndProjects.GetProjectTitle()]);
	println ('// Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	println('(function (root, factory) {');
	println('    if (typeof define === ''function'' && define.amd) {');
	println('        // AMD');
	println('        define([], factory);');
	println('    } else if (typeof module === ''object'' && module.exports) {');
	println('        // Node, CommonJS-like');
	println('        module.exports = factory();');
	println('    } else {');
	println('        // Browser globals (root is window)');
	println('        root.HelpTopics = factory();');
	println('    }');
	println('}(typeof self !== ''undefined'' ? self : this, function () {');
	println('    return {');
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		if nCurTopic < length(aTopicList) - 1 then
			printfln('        %s: %d,', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext])
		else
			printfln('        %s: %d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	println('    };');
	println('}));');
	
end.
%>
