# Project: FPC 3.2.2 Referenz Handbuch
# Generated by HelpNDoc - https://www.helpndoc.com

from enum import Enum

class Help_FreePascal(Enum):
    Lizenz-Bittelesen = 2
    Lizenzen = 278
    GPL-Lizenz = 285
    Deutsch1 = 287
    Englisch1 = 288
    Franzossisch = 289
    Spanisch1 = 290
    Polnisch = 291
    Russisch1 = 292
    MIT-Lizenz = 286
    Deutsch = 279
    Englisch = 280
    Franzosisch = 281
    Spanisch = 282
    Polinsch = 283
    Russisch = 284
    Inhalt = 3
    ListederTabellen = 6
    UberdiesesHandbuch = 7
    Bezeichnungen = 8
    SyntaxDiagramme = 9
    UberdieSprachePascal = 10
    1PascalZeichenundSymbole = 11
    2Konstanten = 23
    3Typen = 27
    4Variablen = 75
    5Objekte = 83
    6Klassen = 97
    7SchnittstellenInterfaces = 124
    8Generics = 133
    9ErweiterteRecords = 147
    10KlassenRecordsundTypen-Helfer = 151
    11ObjektorientiertePascal-Klasse = 159
    12Ausdrucke = 170
    13Anweisungen = 187
    14BenutzungvonFunktionenundProze = 203
    15OperatorenUberladung = 249
    16ProgrammeModuleundBlocke = 259
    17Ausnahmen = 271
    18Assembler = 274
    181Anweisungen = 275
    182ProzedurenundFunktionen = 276
