// Project: FPC 3.2.2 Referenz Handbuch
// Generated by HelpNDoc - https://www.helpndoc.com

unit FreePascal;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
  HELP_Lizenzen = 278; 				 // Topic: "Lizenzen"
  HELP_GPL-Lizenz = 285; 				 // Topic: "GPL - Lizenz"
  HELP_Deutsch1 = 287; 				 // Topic: "Deutsch"
  HELP_Englisch1 = 288; 				 // Topic: "Englisch"
  HELP_Franzossisch = 289; 				 // Topic: "Französsisch"
  HELP_Spanisch1 = 290; 				 // Topic: "Spanisch"
  HELP_Polnisch = 291; 				 // Topic: "Polnisch"
  HELP_Russisch1 = 292; 				 // Topic: "Russisch"
  HELP_MIT-Lizenz = 286; 				 // Topic: "MIT - Lizenz"
  HELP_Deutsch = 279; 				 // Topic: "Deutsch"
  HELP_Englisch = 280; 				 // Topic: "Englisch"
  HELP_Franzosisch = 281; 				 // Topic: "Französisch"
  HELP_Spanisch = 282; 				 // Topic: "Spanisch"
  HELP_Polinsch = 283; 				 // Topic: "Polinsch"
  HELP_Russisch = 284; 				 // Topic: "Russisch"
  HELP_Inhalt = 3; 				 // Topic: "Inhalt"
  HELP_ListederTabellen = 6; 				 // Topic: "Liste der Tabellen"
  HELP_UberdiesesHandbuch = 7; 				 // Topic: "Über dieses Handbuch"
  HELP_Bezeichnungen = 8; 				 // Topic: "Bezeichnungen"
  HELP_SyntaxDiagramme = 9; 				 // Topic: "Syntax Diagramme"
  HELP_UberdieSprachePascal = 10; 				 // Topic: "Über die Sprache Pascal"
  HELP_1PascalZeichenundSymbole = 11; 				 // Topic: "1.  Pascal Zeichen und Symbole"
  HELP_2Konstanten = 23; 				 // Topic: "2.  Konstanten"
  HELP_3Typen = 27; 				 // Topic: "3.  Typen"
  HELP_4Variablen = 75; 				 // Topic: "4.  Variablen"
  HELP_5Objekte = 83; 				 // Topic: "5.  Objekte"
  HELP_6Klassen = 97; 				 // Topic: "6.  Klassen"
  HELP_7SchnittstellenInterfaces = 124; 				 // Topic: "7.  Schnittstellen (Interface's)"
  HELP_8Generics = 133; 				 // Topic: "8.  Generics"
  HELP_9ErweiterteRecords = 147; 				 // Topic: "9.  Erweiterte Record's"
  HELP_10KlassenRecordsundTypen-Helfer = 151; 				 // Topic: "10.  Klassen, Record's, und Typen-Helfer"
  HELP_11ObjektorientiertePascal-Klasse = 159; 				 // Topic: "11.  Objektorientierte Pascal - Klassen"
  HELP_12Ausdrucke = 170; 				 // Topic: "12.  Ausdrücke"
  HELP_13Anweisungen = 187; 				 // Topic: "13.  Anweisungen"
  HELP_14BenutzungvonFunktionenundProze = 203; 				 // Topic: "14.  Benutzung von Funktionen und Prozeduren"
  HELP_15OperatorenUberladung = 249; 				 // Topic: "15.  Operatoren Überladung"
  HELP_16ProgrammeModuleundBlocke = 259; 				 // Topic: "16.  Programme, Module und Blöcke"
  HELP_17Ausnahmen = 271; 				 // Topic: "17.  Ausnahmen"
  HELP_18Assembler = 274; 				 // Topic: "18.  Assembler"
  HELP_181Anweisungen = 275; 				 // Topic: "18.1.  Anweisungen"
  HELP_182ProzedurenundFunktionen = 276; 				 // Topic: "18.2.  Prozeduren und Funktionen"

implementation

end.
