<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;
var
	sModuleName: string;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	sModuleName := ChangeFileExt(ExtractFileName(HndGeneratorInfo.OutputFile), '').Replace(' ', '_');
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('# Project: %s', [HndProjects.GetProjectTitle()]);
	println ('# Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	printfln('class Help_%s:', [sModuleName]);
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		printfln('    %s = %d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	
end.
%>
