<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;
var
	sModuleName: string;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	sModuleName := ChangeFileExt(ExtractFileName(HndGeneratorInfo.OutputFile), '').Replace(' ', '_');
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('// Project: %s', [HndProjects.GetProjectTitle()]);
	println ('// Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	println('using System.Collections.Generic;');
	println ('');
	printfln('public static class Help_%s', [sModuleName]);
	println ('{');
	println('    public static readonly Dictionary<string, int> Topics = new Dictionary<string, int>');
	println('    {');
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		if nCurTopic < length(aTopicList) - 1 then
			printfln('        { "%s", %d },', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext])
		else
			printfln('        { "%s", %d }', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	println('    };');
	println ('}');
	
end.
%>
