<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('// Project: %s', [HndProjects.GetProjectTitle()]);
	println ('// Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	println('const HelpTopics = {');
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		if nCurTopic < length(aTopicList) - 1 then
			printfln('    %s: %d,', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext])
		else
			printfln('    %s: %d', [aTopicList[nCurTopic].HelpId, aTopicList[nCurTopic].HelpContext]);
	end;
	println('};');
	
end.
%>
