<%
var
	aTopicList: THndTopicsInfoArray;
var
	nCurTopic: integer;

begin
	HndGeneratorInfo.CurrentFile := ExtractFileName(HndGeneratorInfo.OutputFile);
	aTopicList := HndTopicsEx.GetTopicListGenerated(False, False);
	
	printfln('// Project: %s', [HndProjects.GetProjectTitle()]);
	println ('// Generated by HelpNDoc - https://www.helpndoc.com');
	println ('');
	println('class HelpTopics {');
	for nCurTopic := 0 to length(aTopicList) - 1 do
	begin
		printfln('    const %s = %d;', [aTopicList[nCurTopic].HelpId.ToUpper(), aTopicList[nCurTopic].HelpContext]);
	end;
	println('}');
	
end.
%>
